sudo: required
dist: trusty
os:
  - linux

language: ruby
rvm:
  - 2.2.2

cache:
  bundler: true
  directories:
    - $HOME/.rvm

install:
  - bash install_dependencies.sh
  - bundle install

addons:
  apt:
    packages:
      - vim-gtk
      - silversearcher-ag
      - ack-grep

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: rake ci
